const accommodationList = [{
  id: '1',
  title: 'Hotel Ubud',
  accommodationType: 'hotel',
  description: 'Hotel Ubud offers a peaceful retreat amidst lush tropical gardens, a 3-minute walk from Ubud Palace.',
  locations: ['Sayan', 'Ubud', 'Indonesia'],
  imageUrl: 'https://t-ec.bstatic.com/images/hotel/max1280x900/831/83163464.jpg',
}, {
  id: '2',
  title: 'Four Seasons Resort',
  accommodationType: 'hotel',
  description: 'Featuring blend of traditional and modern Balinese designs, all units are air conditioned and have a flat-screen TV, wardrobe and personal safe.',
  promoted: true,
  locations: ['Sayan', 'Ubud', 'Indonesia'],
  imageUrl: 'https://s-ec.bstatic.com/images/hotel/max1280x900/831/83160592.jpg',
}, {
  id: '3',
  title: 'Ratna Villa',
  accommodationType: 'home',
  locations: ['Gianyar', 'Ubud', 'Indonesia'],
  description: 'With pool views, Ratna Villa is set in Ubud and has a restaurant, a 24-hour front desk, bar, garden, outdoor pool and sun terrace.',
  imageUrl: 'https://s-ec.bstatic.com/images/hotel/max1280x900/132/132878084.jpg',
}, {
  id: '4',
  title: 'Alila Ubud',
  accommodationType: 'hotel',
  locations: ['Gianyar', 'Ubud', 'Indonesia'],
  description: 'This luxurious hillside retreat sits along the cooling banks of Ayung River in Bali, just 5 km from popular Ubud.',
  imageUrl: 'https://s-ec.bstatic.com/images/hotel/max1280x900/206/206104440.jpg',
}, {
  id: '5',
  title: 'Amora Ubud',
  accommodationType: 'home',
  locations: ['Ubud', 'Indonesia'],
  description: 'Located on a hilltop on the edge of the Campuhan river valley, Amora Ubud Villas offers an infinity outdoor pool and sun terrace.',
  imageUrl: 'https://s-ec.bstatic.com/images/hotel/max1280x900/898/89870103.jpg',
}, {
  id: '6',
  title: 'Villa Santai Kita',
  accommodationType: 'home',
  locations: ['Ubud', 'Indonesia'],
  description: 'The apartment features 2 bedrooms, a flat-screen TV with satellite channels, an equipped kitchen with a microwave and a fridge, a washing machine, and 2 bathrooms with a shower..',
  imageUrl: 'https://s-ec.bstatic.com/images/hotel/max1280x900/167/167450977.jpg',
}];
